name: Deploy AWS

on:
  push:
    branches:
    - master

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'lambda-a.zip'
          exclusions: '*.git* *.github'
          
        - name: deploy lambda-b
          run: |
            aws lambda update-function-code --function-name=lambda-a --zip-file=fileb://lambda-a.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'


# jobs:
#   deploy-lambda:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: build
#         uses: thedoctor0/zip-release@main
#         with:
#           type: 'zip'
#           filename: 'lambda-a.zip'
#           exclusions: '*.git* *.github'
#       - name: deply
#         run: |
#           aws lambda update-function-code --function-name=lambda-a --zip-file=fileb://lambda-a.zip

#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: 'us-west-2'

