name: Deploy AWS

on:
  push:
    branches:
    - master

jobs:
  deploy-lambda:
    runs-on: linuxx
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
        zip lambda-a.zip ./lambda-a
        aws lambda update-function-code --function-name=lambda-a --zip-file=fileb://lambda-a.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
